---
sudo: false

language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6

services:
  - postgresql

before_script:
  - psql -c 'create database ruolo;' -U postgres

before_install:
  - gem update --system
  - gem install bundler
  - gem --version

script:
  # - bundle exec rubocop
  - bundle exec rspec
  # - bundle exec yard

notifications:
  email: false
